apiVersion: v1
kind: Service
metadata:
  name: startupintel-api
  namespace: startupintel
  labels:
    app: startupintel-api
spec:
  type: ClusterIP
  selector:
    app: startupintel-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: startupintel-api-headless
  namespace: startupintel
  labels:
    app: startupintel-api
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: startupintel-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
