"""initial schema

Revision ID: 107c97c4495f
Revises: 
Create Date: 2026-06-09 20:46:36.093402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '107c97c4495f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accelerators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('cohort_count', sa.Integer(), nullable=False),
    sa.Column('follow_on_rate', sa.Float(), nullable=True),
    sa.Column('median_time_to_series_a_months', sa.Float(), nullable=True),
    sa.Column('survival_rate_3yr', sa.Float(), nullable=True),
    sa.Column('unicorn_rate', sa.Float(), nullable=True),
    sa.Column('shutdown_rate', sa.Float(), nullable=True),
    sa.Column('roi_score', sa.Float(), nullable=True),
    sa.Column('industry_focus', sa.String(length=120), nullable=True),
    sa.Column('stage_focus', sa.String(length=80), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_accelerators_roi_score'), 'accelerators', ['roi_score'], unique=False)
    op.create_table('investors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('firm', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('crunchbase_id', sa.String(length=255), nullable=True),
    sa.Column('centrality_score', sa.Float(), nullable=True),
    sa.Column('value_add_score', sa.Float(), nullable=True),
    sa.Column('betweenness', sa.Float(), nullable=True),
    sa.Column('eigenvector', sa.Float(), nullable=True),
    sa.Column('portfolio_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crunchbase_id')
    )
    op.create_index(op.f('ix_investors_firm'), 'investors', ['firm'], unique=False)
    op.create_index(op.f('ix_investors_name'), 'investors', ['name'], unique=False)
    op.create_table('startups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('crunchbase_id', sa.String(length=255), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('hq_city', sa.String(length=120), nullable=True),
    sa.Column('hq_country', sa.String(length=120), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('total_funding_usd', sa.Float(), nullable=True),
    sa.Column('last_funding_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crunchbase_id')
    )
    op.create_index(op.f('ix_startups_domain'), 'startups', ['domain'], unique=True)
    op.create_index(op.f('ix_startups_industry'), 'startups', ['industry'], unique=False)
    op.create_index(op.f('ix_startups_name'), 'startups', ['name'], unique=False)
    op.create_index(op.f('ix_startups_stage'), 'startups', ['stage'], unique=False)
    op.create_table('headcount_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headcount_snapshots_snapshot_date'), 'headcount_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_headcount_snapshots_startup_id'), 'headcount_snapshots', ['startup_id'], unique=False)
    op.create_table('signal_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('emitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_events_emitted_at'), 'signal_events', ['emitted_at'], unique=False)
    op.create_index(op.f('ix_signal_events_event_type'), 'signal_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_signal_events_startup_id'), 'signal_events', ['startup_id'], unique=False)
    op.create_table('startup_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('bot_name', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signal_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_diagnosis', sa.Text(), nullable=True),
    sa.Column('similar_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'bot_name', 'computed_at', name='uq_startup_bot_computed_at')
    )
    op.create_index(op.f('ix_startup_scores_bot_name'), 'startup_scores', ['bot_name'], unique=False)
    op.create_index(op.f('ix_startup_scores_computed_at'), 'startup_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_startup_scores_startup_id'), 'startup_scores', ['startup_id'], unique=False)
    op.create_table('termsheet_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('founder_friendliness_score', sa.Float(), nullable=False),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clause_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_benchmark', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_diagnosis', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('termsheet_analyses')
    op.drop_index(op.f('ix_startup_scores_startup_id'), table_name='startup_scores')
    op.drop_index(op.f('ix_startup_scores_computed_at'), table_name='startup_scores')
    op.drop_index(op.f('ix_startup_scores_bot_name'), table_name='startup_scores')
    op.drop_table('startup_scores')
    op.drop_index(op.f('ix_signal_events_startup_id'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_event_type'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_emitted_at'), table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_index(op.f('ix_headcount_snapshots_startup_id'), table_name='headcount_snapshots')
    op.drop_index(op.f('ix_headcount_snapshots_snapshot_date'), table_name='headcount_snapshots')
    op.drop_table('headcount_snapshots')
    op.drop_index(op.f('ix_startups_stage'), table_name='startups')
    op.drop_index(op.f('ix_startups_name'), table_name='startups')
    op.drop_index(op.f('ix_startups_industry'), table_name='startups')
    op.drop_index(op.f('ix_startups_domain'), table_name='startups')
    op.drop_table('startups')
    op.drop_index(op.f('ix_investors_name'), table_name='investors')
    op.drop_index(op.f('ix_investors_firm'), table_name='investors')
    op.drop_table('investors')
    op.drop_index(op.f('ix_accelerators_roi_score'), table_name='accelerators')
    op.drop_table('accelerators')
    # ### end Alembic commands ###
