"""add uploaded_files table

Revision ID: 6eacdce62a56
Revises: 75b01859d068
Create Date: 2026-06-14 16:31:12.551513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eacdce62a56'
down_revision: Union[str, None] = '75b01859d068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('startup_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_category', sa.String(length=50), nullable=False),
    sa.Column('file_description', sa.Text(), nullable=True),
    sa.Column('virus_scan_status', sa.String(length=20), nullable=False),
    sa.Column('virus_scan_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('access_url', sa.String(length=500), nullable=True),
    sa.Column('access_url_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_deleted_at'), 'uploaded_files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_organization_id'), 'uploaded_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_startup_id'), 'uploaded_files', ['startup_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_startup_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_organization_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_deleted_at'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
